test_programmer/produk/urls.py
from django.urls import path

from . import views

app_name = 'produk'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    # Kategori
    path('index_kategori/', views.IndexKategori.as_view(), name='index_kategori'),
    path('add_kategori/', views.AddKategori.as_view(), name='add_kategori'),
    path('edit_kategori/<pk>', views.EditKategori.as_view(), name='edit_kategori'),
    path('delete_kategori/<int:kategori_id>/', views.delete_kategori, name='delete_kategori'),
    # Produk
    path('index_produk/', views.Index.as_view(), name='index_produk'),
    path('add_produk/', views.AddProduk.as_view(), name='add_produk'),
    path('edit_produk/<pk>', views.EditProduk.as_view(), name='edit_produk'),
    path('delete_produk/<int:produk_id>/', views.delete_produk, name='delete_produk'),
    # Status
    path('index_status/', views.IndexStatus.as_view(), name='index_status'),
    path('add_status/', views.AddStatus.as_view(), name='add_status'),
    path('edit_status/<pk>', views.EditStatus.as_view(), name='edit_status'),
    path('delete_status/<int:status_id>/', views.delete_status, name='delete_status'),
    # API Produk
    path('api/produk/', views.ProdukApi.as_view(), name='produk-list'),
    path('api/add_produk/' , views.ProdukCreateApi.as_view(), name='produk-create'),
    path('api/edit_produk/<int:pk>/', views.ProdukUpdateApi.as_view(), name='produk-update'),
    path('api/delete_produk/<int:pk>/', views.ProdukDeleteApi.as_view(), name='produk-delete'),
    # API Kategori
    path('api/kategori/', views.KategoriApi.as_view(), name='kategori-list'),
    path('api/add_kategori/' , views.KategoriCreateApi.as_view(), name='kategori-create'),
    path('api/edit_kategori/<int:pk>/', views.KategoriUpdateApi.as_view(), name='kategori-update'),
    path('api/delete_kategori/<int:pk>/', views.KategoriDeleteApi.as_view(), name='kategori-delete'),
    # API Status
    path('api/status/', views.StatusApi.as_view(), name='status-list'),
    path('api/add_status/' , views.StatusCreateApi.as_view(), name='status-create'),
    path('api/edit_status/<int:pk>/', views.StatusUpdateApi.as_view(), name='status-update'),
    path('api/delete_status/<int:pk>/', views.StatusDeleteApi.as_view(), name='status-delete'),

]

test_programmer/test_programmer/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static  import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produk.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

test_programmer/produk/models.py
from django.db import models


# Create your models here.

class Status(models.Model):
    
    nama_status = models.CharField(max_length=255)

    def __str__(self):
        return self.nama_status

class Kategori(models.Model):
    nama_kategori = models.CharField(max_length=255)

    def __str__(self):
        return self.nama_kategori
    
class Produk(models.Model):
    from .models  import Status  
    from .models  import Kategori  

    nama_produk = models.CharField(max_length=255)
    harga = models.DecimalField(max_digits=10, decimal_places=2)
    kategori = models.ForeignKey(Kategori, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)

    def __str__(self):
        return self.nama_produk

test_programmer/templates/kategori/add.html
{% extends "layouts/index.html" %} {% block content %}
<div class="container-fluid">
  <h1 class="h3 mb-2 text-gray-800">Tambah Kategori</h1>
  <p class="mb-4">Packclese</p>
  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Tambah Kategori</h6>
    </div>
    <div class="card-body">
      <!-- form start -->
      <form action="" method="POST">
        {% csrf_token %}
        
        <!-- input nama_kategori -->
        <div class="form-group">
          <label for="id_nama_kategori">Nama</label>
          <input
            type="text"
            name="nama_kategori"
            class="form-control {% if form.errors.nama_kategori %}is-invalid{% endif %}"
            value="{{ form.cleaned_data.nama_kategori }}"
            placeholder="Nama Kategori"
            required
            id="id_nama_kategori"
          />
          {% for error in form.errors.nama_kategori %}
          <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
        <!-- end input nama_kategori -->

        <!-- button submit -->
        <div class="form-group">
          <div class="text-left">
            <button type="submit" class="btn btn-success">Add</button>
          </div>
        </div>
        <!-- end button submit -->
      </form>
      <!-- end form -->
    </div>
  </div>
</div>
{% endblock %}

test_programmer/templates/kategori/edit.html
{% extends "layouts/index.html" %} {% block content %}
<div class="container-fluid">
  <h1 class="h3 mb-2 text-gray-800">Tambah Kategori</h1>
  <p class="mb-4">Packclese</p>
  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Tambah Kategori</h6>
    </div>
    <div class="card-body">
      <!-- form start -->
      <form action="" method="POST">
        {% csrf_token %}

        <!-- input nama_kategori -->
        <div class="form-group">
          <label for="id_nama_kategori">Nama</label>
          <input
            type="text"
            name="nama_kategori"
            class="form-control {% if form.errors.nama_kategori %}is-invalid{% endif %}"
            value="{{ kategori.nama_kategori }}"
            placeholder="Nama Kategori"
            required
            id="id_nama_kategori"
          />
          {% for error in form.errors.nama_kategori %}
          <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
        <!-- end input nama_kategori -->

        <!-- button submit -->
        <div class="form-group">
          <div class="text-left">
            <button type="submit" class="btn btn-success">Edit</button>
          </div>
        </div>
        <!-- end button submit -->
      </form>
      <!-- end form -->
    </div>
  </div>
</div>
{% endblock %}

test_programmer/templates/kategori/index.html
{% extends "layouts/index.html" %} 
{% block content %}
<div class="container-fluid">
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">List Kategori</h1>
  <p class="mb-4">Data Kategori</p>
  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">List Kategori</h6>
    </div>
    <div class="card-body">
      <!-- Start Tabel -->
      <div class="table-responsive">
        <table
          class="table table-bordered"
          id="dataTable"
          width="100%"
          cellspacing="0"
        >
          <thead>
            <tr>
              <th>Nama Kategori</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for kategori in object_list %}
            <tr>
              <td>{{ kategori.nama_kategori }}</td>
              <td>
                <a href="{% url 'produk:edit_kategori' kategori.id %}" class="btn btn-m btn-warning"
                  ><i class="fas fa-edit"></i
                ></a>
                <a
                  href="#"
                  class="btn btn-danger"
                  data-toggle="modal"
                  data-target="#exampleModal{{ kategori.id }}"
                >
                  <i class="fas fa-trash"></i>
                </a>
              </td>
            </tr>

            <!-- Start Modal -->
            <div
              class="modal fade"
              id="exampleModal{{ kategori.id }}"
              tabindex="-1"
              aria-labelledby="exampleModalLabel"
              aria-hidden="true"
            >
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Hapus</h5>
                    <button
                      type="button"
                      class="close"
                      data-dismiss="modal"
                      aria-label="Close"
                    >
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Apakah kamu yakin untuk menghapusnya ?
                  </div>
                  <div class="modal-footer">
                    <button
                      type="button"
                      class="btn btn-secondary"
                      data-dismiss="modal"
                    >
                      Batal
                    </button>
                    <a href="{% url 'produk:delete_kategori' kategori.id %}" class="btn btn-danger">Hapus</a>
                  </div>
                </div>
              </div>
            </div>
            <!-- End Modal -->

            {% endfor %}
          </tbody>
        </table>
        <!-- End Tabel -->
      </div>
    </div>
  </div>
</div>
{% endblock %}