test_programmer/produk/urls.py
from django.urls import path

from . import views

app_name = 'produk'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    # Kategori
    path('index_kategori/', views.IndexKategori.as_view(), name='index_kategori'),
    path('add_kategori/', views.AddKategori.as_view(), name='add_kategori'),
    path('edit_kategori/<pk>', views.EditKategori.as_view(), name='edit_kategori'),
    path('delete_kategori/<int:kategori_id>/', views.delete_kategori, name='delete_kategori'),
    # Produk
    path('index_produk/', views.Index.as_view(), name='index_produk'),
    path('add_produk/', views.AddProduk.as_view(), name='add_produk'),
    path('edit_produk/<pk>', views.EditProduk.as_view(), name='edit_produk'),
    path('delete_produk/<int:produk_id>/', views.delete_produk, name='delete_produk'),
    # Status
    path('index_status/', views.IndexStatus.as_view(), name='index_status'),
    path('add_status/', views.AddStatus.as_view(), name='add_status'),
    path('edit_status/<pk>', views.EditStatus.as_view(), name='edit_status'),
    path('delete_status/<int:status_id>/', views.delete_status, name='delete_status'),
    # API Produk
    path('api/produk/', views.ProdukApi.as_view(), name='produk-list'),
    path('api/add_produk/' , views.ProdukCreateApi.as_view(), name='produk-create'),
    path('api/edit_produk/<int:pk>/', views.ProdukUpdateApi.as_view(), name='produk-update'),
    path('api/delete_produk/<int:pk>/', views.ProdukDeleteApi.as_view(), name='produk-delete'),
    # API Kategori
    path('api/kategori/', views.KategoriApi.as_view(), name='kategori-list'),
    path('api/add_kategori/' , views.KategoriCreateApi.as_view(), name='kategori-create'),
    path('api/edit_kategori/<int:pk>/', views.KategoriUpdateApi.as_view(), name='kategori-update'),
    path('api/delete_kategori/<int:pk>/', views.KategoriDeleteApi.as_view(), name='kategori-delete'),
    # API Status
    path('api/status/', views.StatusApi.as_view(), name='status-list'),
    path('api/add_status/' , views.StatusCreateApi.as_view(), name='status-create'),
    path('api/edit_status/<int:pk>/', views.StatusUpdateApi.as_view(), name='status-update'),
    path('api/delete_status/<int:pk>/', views.StatusDeleteApi.as_view(), name='status-delete'),

]

test_programmer/test_programmer/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static  import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produk.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

test_programmer/produk/models.py
from django.db import models


# Create your models here.

class Status(models.Model):
    
    nama_status = models.CharField(max_length=255)

    def __str__(self):
        return self.nama_status

class Kategori(models.Model):
    nama_kategori = models.CharField(max_length=255)

    def __str__(self):
        return self.nama_kategori
    
class Produk(models.Model):
    from .models  import Status  
    from .models  import Kategori  

    nama_produk = models.CharField(max_length=255)
    harga = models.DecimalField(max_digits=10, decimal_places=2)
    kategori = models.ForeignKey(Kategori, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)

    def __str__(self):
        return self.nama_produk

test_programmer/produk/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from produk.models import Produk
from produk.models import Kategori
from produk.models import Status
from produk.ProdukForm import ProdukForm, KategoriForm, StatusForm
from django.shortcuts import render, redirect

class Home(ListView):
    queryset = Produk.objects.all()
    template_name = 'layouts/index.html'

# view Produk
class Index(ListView):
    queryset = Produk.objects.all()
    template_name = 'produk/index.html' 

class AddProduk(CreateView):
    form_class = ProdukForm
    template_name = 'produk/add.html'
    success_url = reverse_lazy('produk:index_produk')

    def form_valid(self, form):
        nama_produk = form.cleaned_data['nama_produk']
        harga = form.cleaned_data['harga']
        
        # Cek panjang nama_produk
        if len(nama_produk) > 100:
            form.add_error('nama_produk', 'Nama produk terlalu panjang. Maksimal 100 karakter.')
            return self.form_invalid(form)

        # Cek apakah nama_produk sudah ada
        if Produk.objects.filter(nama_produk=nama_produk).exists():
            form.add_error('nama_produk', 'Nama produk sudah ada.')
            return self.form_invalid(form)
        
        if harga < 0:
            form.add_error('harga', 'Harga tidak boleh kurang dari 0.')
            return self.form_invalid(form)
        
        return super().form_valid(form)
    
        

class EditProduk(UpdateView):
    model = Produk
    form_class = ProdukForm
    template_name = 'produk/edit.html'
    success_url = reverse_lazy('produk:index_produk')

    def form_valid(self, form):
        nama_produk = form.cleaned_data['nama_produk']
        harga = form.cleaned_data['harga']
        
        # Cek panjang nama_produk
        if len(nama_produk) > 100:
            form.add_error('nama_produk', 'Nama produk terlalu panjang. Maksimal 100 karakter.')
            return self.form_invalid(form)

        # Cek apakah nama_produk sudah ada
        if Produk.objects.filter(nama_produk=nama_produk).exclude(id=self.object.id).exists():
            form.add_error('nama_produk', 'Nama produk sudah ada.')
            return self.form_invalid(form)
        
        if harga < 0:
            form.add_error('harga', 'Harga tidak boleh kurang dari 0.')
            return self.form_invalid(form)
        
        return super().form_valid(form)

def delete_produk(request, produk_id):
    produk = Produk.objects.get(id=produk_id)
    produk.delete()
    return redirect('produk:index_produk')

# view Kategori
class IndexKategori(ListView):
    queryset = Kategori.objects.all()
    template_name = 'kategori/index.html'

class AddKategori(CreateView):
    form_class = KategoriForm
    template_name = 'kategori/add.html'
    success_url = reverse_lazy('produk:index_kategori')

    def form_valid(self, form):
        nama_kategori = form.cleaned_data['nama_kategori']
        
        # Cek panjang nama_kategori
        if len(nama_kategori) > 100:
            form.add_error('nama_kategori', 'Nama kategori terlalu panjang. Maksimal 100 karakter.')
            return self.form_invalid(form)

        # Cek apakah nama_kategori sudah ada
        if Kategori.objects.filter(nama_kategori=nama_kategori).exists():
            form.add_error('nama_kategori', 'Nama kategori sudah ada.')
            return self.form_invalid(form)
        
        return super().form_valid(form)

class EditKategori(UpdateView):
    model = Kategori
    form_class = KategoriForm
    template_name = 'kategori/edit.html'
    success_url = reverse_lazy('produk:index_kategori')

    def form_valid(self, form):
        nama_kategori = form.cleaned_data['nama_kategori']
        
        # Cek panjang nama_kategori
        if len(nama_kategori) > 100:
            form.add_error('nama_kategori', 'Nama kategori terlalu panjang. Maksimal 100 karakter.')
            return self.form_invalid(form)

        # Cek apakah nama_kategori sudah ada
        if Kategori.objects.filter(nama_kategori=nama_kategori).exclude(id=self.object.id).exists():
            form.add_error('nama_kategori', 'Nama kategori sudah ada.')
            return self.form_invalid(form)
        
        return super().form_valid(form)

def delete_kategori(request, kategori_id):
    kategori = Kategori.objects.get(id=kategori_id)
    kategori.delete()
    return redirect('produk:index_kategori')

# view Status
class IndexStatus(ListView):
    queryset = Status.objects.all()
    template_name = 'status/index.html'

class AddStatus(CreateView):
    form_class = StatusForm
    template_name = 'status/add.html'
    success_url = reverse_lazy('produk:index_status')

    def form_valid(self, form):
        nama_status = form.cleaned_data['nama_status']
        
        # Cek panjang nama_status
        if len(nama_status) > 100:
            form.add_error('nama_status', 'Nama status terlalu panjang. Maksimal 100 karakter.')
            return self.form_invalid(form)

        # Cek apakah nama_status sudah ada
        if Status.objects.filter(nama_status=nama_status).exists():
            form.add_error('nama_status', 'Nama status sudah ada.')
            return self.form_invalid(form)
        
        return super().form_valid(form)

class EditStatus(UpdateView):
    model = Status
    form_class = StatusForm
    template_name = 'status/edit.html'
    success_url = reverse_lazy('produk:index_status')

    def form_valid(self, form):
        nama_status = form.cleaned_data['nama_status']
        
        # Cek panjang nama_status
        if len(nama_status) > 100:
            form.add_error('nama_status', 'Nama status terlalu panjang. Maksimal 100 karakter.')
            return self.form_invalid(form)

        # Cek apakah nama_status sudah ada
        if Status.objects.filter(nama_status=nama_status).exclude(id=self.object.id).exists():
            form.add_error('nama_status', 'Nama status sudah ada.')
            return self.form_invalid(form)
        
        return super().form_valid(form)

def delete_status(request, status_id):
    status = Status.objects.get(id=status_id)
    status.delete()
    return redirect('produk:index_status')

# view API Produk

from rest_framework import generics
from .serializers import ProdukSerializer


class ProdukApi(generics.ListCreateAPIView):
    queryset = Produk.objects.all()
    serializer_class = ProdukSerializer

class ProdukCreateApi(generics.CreateAPIView):
    queryset = Produk.objects.all()
    serializer_class = ProdukSerializer

class ProdukUpdateApi(generics.UpdateAPIView):
    queryset = Produk.objects.all()
    serializer_class = ProdukSerializer

class ProdukDeleteApi(generics.DestroyAPIView):
    queryset = Produk.objects.all()
    serializer_class = ProdukSerializer

# view API Kategori

from .serializers import KategoriSerializer

class KategoriApi(generics.ListCreateAPIView):
    queryset = Kategori.objects.all()
    serializer_class = KategoriSerializer

class KategoriCreateApi(generics.CreateAPIView):
    queryset = Kategori.objects.all()
    serializer_class = KategoriSerializer

class KategoriUpdateApi(generics.UpdateAPIView):
    queryset = Kategori.objects.all()
    serializer_class = KategoriSerializer

class KategoriDeleteApi(generics.DestroyAPIView):   
    queryset = Kategori.objects.all()
    serializer_class = KategoriSerializer

# view API Status

from .serializers import StatusSerializer

class StatusApi(generics.ListCreateAPIView):
    queryset = Status.objects.all()
    serializer_class = StatusSerializer

class StatusCreateApi(generics.CreateAPIView):
    queryset = Status.objects.all()
    serializer_class = StatusSerializer

class StatusUpdateApi(generics.UpdateAPIView):
    queryset = Status.objects.all()
    serializer_class = StatusSerializer

class StatusDeleteApi(generics.DestroyAPIView):
    queryset = Status.objects.all()
    serializer_class = StatusSerializer

test_programmer/templates/produk/add.html
{% extends "layouts/index.html" %} {% block content %}
<div class="container-fluid">
  <h1 class="h3 mb-2 text-gray-800">Tambah Produk</h1>
  <p class="mb-4">Packclese</p>
  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Tambah Produk</h6>
    </div>
    <div class="card-body">
      <!-- form start -->
      <form action="" method="POST">
        {% csrf_token %}

        <!-- input nama_produk -->
        <div class="form-group">
          <label for="id_nama_produk">Nama</label>
          <input
            type="text"
            name="nama_produk"
            class="form-control {% if form.errors.nama_produk %}is-invalid{% endif %}"
            value="{{ form.cleaned_data.nama_produk }}"
            placeholder="Nama Produk"
            required
            id="id_nama_produk"
          />
          {% for error in form.errors.nama_produk %}
          <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
        <!-- end input nama_produk -->

        <!-- input kategori -->
        <div class="form-group">
          <label for="id_kategori">Kategori</label>
          <select class="form-control {% if form.errors.kategori %}is-invalid{% endif %}" name="kategori" id="id_kategori">
            <option disabled selected>Pilih Kategori</option>
            {% for id, nama_kategori in form.kategori.field.choices %} 
            <option value="{{ id }}" {% if form.cleaned_data.kategori.id == id %}selected{% endif %}>{{ nama_kategori }}</option>
            {% endfor %}
          </select>
          {% for error in form.errors.kategori %}
          <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
        <!-- end input kategori -->

        <!-- input status -->
        <div class="form-group">
          <label for="id_status">Status</label>
          <select
            class="form-control {% if form.errors.status %}is-invalid{% endif %}"
            name="status"
            id="id_status"
          >
            <option disabled selected>Pilih Status</option>
            {% for id, nama_status in form.status.field.choices %} 
            <option value="{{ id }}" {% if form.cleaned_data.status.id == id %}selected{% endif %}>{{ nama_status }}</option>
            {% endfor %}
          </select>
          {% for error in form.errors.status %}
          <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
        <!-- end input status -->

        <!-- input harga -->
        <div class="form-group">
          <label for="id_harga">Harga</label>
          <input
            type="number"
            name="harga"
            class="form-control {% if form.errors.harga %}is-invalid{% endif %}"
            value="{{ form.cleaned_data.harga }}"
            placeholder="Harga Produk"
            required
            id="id_harga"
          />
          {% for error in form.errors.harga %}
          <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
        <!-- end input harga -->

        <!-- button submit -->
        <div class="form-group">
          <div class="text-left">
            <button type="submit" class="btn btn-success">Add</button>
          </div>
        </div>
        <!-- end button submit -->
      </form>
      <!-- end form -->
    </div>
  </div>
</div>
{% endblock %}

test_programmer/templates/produk/edit.html
{% extends "layouts/index.html" %} {% block content %}
<div class="container-fluid">
  <h1 class="h3 mb-2 text-gray-800">Edit Produk</h1>
  <p class="mb-4">Packclese</p>
  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Edit Produk</h6>
    </div>
    <div class="card-body">
      <!-- form start -->
      <form action="" method="POST">
        {% csrf_token %}

        <!-- input nama_produk -->
        <div class="form-group">
          <label for="id_nama_produk">Nama</label>
          <input
            type="text"
            name="nama_produk"
            class="form-control {% if form.errors.nama_produk %}is-invalid{% endif %}"
            value="{{ produk.nama_produk }}"
            placeholder="Nama Produk"
            required
            id="id_nama_produk"
          />
          {% for error in form.errors.nama_produk %}
          <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
        <!-- end input nama_produk -->

        <!-- input kategori -->
        <div class="form-group">
          <label for="id_kategori">Kategori</label>
          <select class="form-control {% if form.errors.kategori %}is-invalid{% endif %}" name="kategori" id="id_kategori">
            <option disabled selected>Pilih Kategori</option>
            {% for id, nama_kategori in form.kategori.field.choices %} 
            <option value="{{ id }}"  {% if id == produk.kategori.id %}selected{% endif %}>{{ nama_kategori }}</option>
            {% endfor %}
          </select>
          {% for error in form.errors.kategori %}
          <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
        <!-- end input kategori -->

        <!-- input status -->
        <div class="form-group">
          <label for="id_status">Status</label>
          <select
            class="form-control {% if form.errors.status %}is-invalid{% endif %}"
            name="status"
            id="id_status"
          >
          <option disabled selected>Pilih Status</option>
          {% for id, nama_status in form.status.field.choices %} 
          <option value="{{ id }}" {% if id == produk.status.id %}selected {% endif %}>{{ nama_status }}</option> 
          {% endfor %}
          </select>
          {% for error in form.errors.status %}
          <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
        <!-- end input status -->

        <!-- input harga -->
        <div class="form-group">
          <label for="id_harga">Harga</label>
          <input
            type="number"
            name="harga"
            class="form-control {% if form.errors.harga %}is-invalid{% endif %}"
            value="{{ produk.harga }}"
            placeholder="Harga Layanan"
            required
            id="id_harga"
          />
          {% for error in form.errors.harga %}
          <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
        <!-- end input harga -->

        <!-- button submit -->
        <div class="form-group">
          <div class="text-left">
            <button type="submit" class="btn btn-success">Edit</button>
          </div>
        </div>
        <!-- end button submit -->
      </form>
      <!-- end form -->
    </div>
  </div>
</div>
{% endblock %}

test_programmer/templates/produk/index.html
{% extends "layouts/index.html" %} {% block content %}
<div class="container-fluid">
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">List Layanan</h1>
  <p class="mb-4">Data Layanan</p>
  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">List Layanan</h6>
    </div>
    <div class="card-body">
      <!-- Start Tabel -->
      <div class="table-responsive">
        <table
          class="table table-bordered"
          id="dataTable"
          width="100%"
          cellspacing="0"
        >
          <thead>
            <tr>
              <th>Nama</th>
              <th>Harga</th>
              <th>Kategori</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for produk in object_list %}
            <tr>
              <td>{{ produk.nama_produk }}</td>
              <td>{{ produk.harga }}</td>
              <td>{{ produk.kategori }}</td>
              <td>{{ produk.status }}</td>
              <td>
                <a href="#" class="btn btn-m btn-warning"
                  ><i class="fas fa-edit"></i
                ></a>
                <a
                  href="{{produk.id}}"
                  class="btn btn-danger"
                  data-toggle="modal"
                  data-target="#exampleModal{{ produk.id }}"
                >
                  <i class="fas fa-trash"></i>
                </a>
              </td>
            </tr>

            <!-- Start Modal -->
            <div
              class="modal fade"
              id="exampleModal{{ produk.id }}"
              tabindex="-1"
              aria-labelledby="exampleModalLabel"
              aria-hidden="true"
            >
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Hapus</h5>
                    <button
                      type="button"
                      class="close"
                      data-dismiss="modal"
                      aria-label="Close"
                    >
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Apakah kamu yakin untuk menghapusnya ?
                  </div>
                  <div class="modal-footer">
                    <button
                      type="button"
                      class="btn btn-secondary"
                      data-dismiss="modal"
                    >
                      Batal
                    </button>
                    <a href="#" class="btn btn-danger">Hapus</a>
                  </div>
                </div>
              </div>
            </div>
            <!-- End Modal -->

            {% endfor %}
          </tbody>
        </table>
        <!-- End Tabel -->
      </div>
    </div>
  </div>
</div>
{% endblock %}